# Generated by Django 4.1.3 on 2022-11-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('address', models.TextField()),
                ('email', models.CharField(max_length=122)),
                ('number', models.CharField(max_length=12)),
                ('tiffin_center', models.CharField(max_length=122)),
            ],
        ),
    ]
